// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2G1Bei_qSp_bfiWt7Tr0BnXIh3eMFuc',
    appId: '1:288465800729:web:0104c613d1b3240ee96488',
    messagingSenderId: '288465800729',
    projectId: 'buskirala-ekip',
    authDomain: 'buskirala-ekip.firebaseapp.com',
    storageBucket: 'buskirala-ekip.firebasestorage.app',
    measurementId: 'G-BSWT0362TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjIFnzMkW7oyRE4jdhwL7W9WNNaAcTbz0',
    appId: '1:288465800729:android:e683f719d7d005b7e96488',
    messagingSenderId: '288465800729',
    projectId: 'buskirala-ekip',
    storageBucket: 'buskirala-ekip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97U4OD27rpQ3V-cDBiBFjN4-cGI9Cigo',
    appId: '1:288465800729:ios:aecbcf000c417bcae96488',
    messagingSenderId: '288465800729',
    projectId: 'buskirala-ekip',
    storageBucket: 'buskirala-ekip.firebasestorage.app',
    iosBundleId: 'com.buskirala.buskiralaEkip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97U4OD27rpQ3V-cDBiBFjN4-cGI9Cigo',
    appId: '1:288465800729:ios:aecbcf000c417bcae96488',
    messagingSenderId: '288465800729',
    projectId: 'buskirala-ekip',
    storageBucket: 'buskirala-ekip.firebasestorage.app',
    iosBundleId: 'com.buskirala.buskiralaEkip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo2G1Bei_qSp_bfiWt7Tr0BnXIh3eMFuc',
    appId: '1:288465800729:web:3170a6516522db77e96488',
    messagingSenderId: '288465800729',
    projectId: 'buskirala-ekip',
    authDomain: 'buskirala-ekip.firebaseapp.com',
    storageBucket: 'buskirala-ekip.firebasestorage.app',
    measurementId: 'G-X7MVZRSK4B',
  );
}
